name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 每次推送到 main 分支时触发
  workflow_dispatch:  # 支持手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 构建环境

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 登录 Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: shihao915@gmail.com  # Docker Hub 用户名
        password: 456852shiHAO     # Docker Hub 密码

    # 构建并推送 Docker 镜像（双架构支持）
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .  # 使用仓库根目录作为构建上下文
        file: ./docker/Dockerfile.cpu  # 指定使用的 Dockerfile 路径
        push: true  # 推送到 Docker Hub
        tags: hs666-ai/vllm:latest  # 设置镜像标签
        platforms: linux/amd64,linux/arm64  # 构建双架构镜像
